name: Android Lint & Build on Develop PR

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'android/**'

jobs:
  lint-build-dev:
    name: Lint and Build Dev Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Restore google-services.json (dev)
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON_DEV }}
        run: echo "$DATA" | base64 -d > app/src/dev/google-services.json

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Run Android Lint Dev Debug
        run: ./gradlew lintDevDebug

      - name: Build Dev Debug APK
        run: ./gradlew assembleDevDebug

  lint-build-prod:
    name: Lint and Build Prod Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Restore google-services.json (prod)
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON_PROD }}
        run: echo "$DATA" | base64 -d > app/src/prod/google-services.json

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Run Android Lint Prod Debug
        run: ./gradlew lintProdDebug

      - name: Build Prod Debug APK
        run: ./gradlew assembleProdDebug
