name: Lint & Build

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'android/**'

defaults:
  run:
    working-directory: android

jobs:
  lint-build-dev:
    name: Dev
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Restore google-services.json (dev)
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON_DEV }}
        run: |
          mkdir -p app/src/dev
          echo "$DATA" | base64 -d > app/src/dev/google-services.json

      - name: Restore Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.jks

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Run Android Lint Dev Debug
        run: ./gradlew lintDevDebug

      - name: Run Android Lint Dev Release
        run: ./gradlew lintDevRelease

      - name: Build Dev Debug APK
        run: ./gradlew assembleDevDebug

      - name: Build devRelease AAB
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/android/release.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS_DEV: ${{ secrets.KEY_ALIAS_DEV }}
          KEY_PASSWORD_DEV: ${{ secrets.KEY_PASSWORD_DEV }}
        run: ./gradlew bundleDevRelease

  lint-build-prod:
    name: Prod
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Restore google-services.json (prod)
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON_PROD }}
        run: |
          mkdir -p app/src/prod
          echo "$DATA" | base64 -d > app/src/prod/google-services.json

      - name: Restore Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.jks

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Run Android Lint Prod Debug
        run: ./gradlew lintProdDebug

      - name: Run Android Lint Prod Release
        run: ./gradlew lintProdRelease

      - name: Build Prod Debug APK
        run: ./gradlew assembleProdDebug

      - name: Build prodRelease AAB
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/android/release.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS_PROD: ${{ secrets.KEY_ALIAS_PROD }}
          KEY_PASSWORD_PROD: ${{ secrets.KEY_PASSWORD_PROD }}
        run: ./gradlew bundleProdRelease
