name: Android Lint & Build on Develop PR

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'android/**'

jobs:
  lint-build:
    name: Lint and Build Debug Variants
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 1

      - name: Restore google‑services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$DATA" | base64 -d > app/google-services.json

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Run Android Lint
        run: ./gradlew lint

      - name: Build Dev Debug APK
        run: ./gradlew assembleDevDebug

      - name: Build Prod Debug APK
        run: ./gradlew assembleProdDebug
