name: Build & Deploy

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'android/**'

defaults:
  run:
    working-directory: android

jobs:
  staging:
    if: github.ref == 'refs/heads/develop'
    name: Dev
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore google‑services.json (dev)
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON_DEV }}
        run: echo "$DATA" | base64 -d > app/src/dev/google-services.json

      - name: Restore Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.jks

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Read staging versionName
        id: ver
        run: echo "VERSION_NAME=$(head -n1 whatsNew/dev/whatsnew-en-US)" >> $GITHUB_ENV

      - name: Remove first line from whatsnew-en-US
        run: sed -i '1d' whatsNew/dev/whatsnew-en-US

      - name: Calculate adjusted version code
        id: adjust_run_code
        run: echo "adjusted_run_code=$((GITHUB_RUN_NUMBER + 2))" >> $GITHUB_ENV
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}

      - name: Add versionCode & versionName
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: ./app/build.gradle.kts
          versionCode: ${{ env.adjusted_run_code }}
          versionName: ${{ env.VERSION_NAME }}

      - name: Build devRelease AAB
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/android/release.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS_DEV: ${{ secrets.KEY_ALIAS_DEV }}
          KEY_PASSWORD_DEV: ${{ secrets.KEY_PASSWORD_DEV }}
        run: ./gradlew bundleDevRelease

      - name: Publish to Internal track (Staging)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_DEV }}
          packageName: com.suyogbauskar.yccealumni.dev
          releaseFiles: app/build/outputs/bundle/devRelease/app-dev-release.aab
          track: internal
          whatsNewDirectory: whatsNew/dev

  production:
    if: github.ref == 'refs/heads/main'
    name: Prod
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore google‑services.json (prod)
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON_PROD }}
        run: echo "$DATA" | base64 -d > app/src/prod/google-services.json

      - name: Restore Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.jks

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Read production versionName
        id: ver
        run: echo "VERSION_NAME=$(head -n1 whatsNew/prod/whatsnew-en-US)" >> $GITHUB_ENV

      - name: Remove first line from whatsnew-en-US
        run: sed -i '1d' whatsNew/prod/whatsnew-en-US

      - name: Calculate adjusted version code
        id: adjust_run_code
        run: echo "adjusted_run_code=$((GITHUB_RUN_NUMBER + 2))" >> $GITHUB_ENV
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}

      - name: Add versionCode & versionName
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ env.adjusted_run_code }}
          versionName: ${{ env.VERSION_NAME }}

      - name: Build prodRelease AAB
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/android/release.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS_PROD: ${{ secrets.KEY_ALIAS_PROD }}
          KEY_PASSWORD_PROD: ${{ secrets.KEY_PASSWORD_PROD }}
        run: ./gradlew bundleProdRelease

      - name: Publish to Production track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_PROD }}
          packageName: com.suyogbauskar.yccealumni
          releaseFiles: app/build/outputs/bundle/prodRelease/app-prod-release.aab
          track: internal
          whatsNewDirectory: whatsNew/prod
